# A workflow to run a simple test that actually goes to WML

name: CI-basic

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  basic-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Runs a single command using the runners shell
      # export DOWML_CREDENTIALS="{'apikey': ${WML_PROD_APIKEY}, 'url': ${WML_PROD_URL}, 'space_id': ${WML_PROD_SPACE_ID} }"
      - name: Run basic tests
        env:
          WML_PROD_APIKEY: '${{secrets.WML_PROD_APIKEY}}'
          WML_PROD_URL: '${{secrets.WML_PROD_URL}}'
          WML_SPACE_ID: '${{secrets.WML_PROD_SPACE_ID}}'
        run: |
          export DOWML_CREDENTIALS="{'apikey': ${WML_PROD_APIKEY}, 'url': ${WML_PROD_URL}, 'space_id': ${WML_PROD_SPACE_ID} }"
          echo ${WML_PROD_APIKEY}
          echo ${WML_PROD_URL}
          echo ${WML_SPACE_ID}
          echo ${DOWML_CREDENTIALS}
          make basic
