# A workflow to run tests that actually goes to WML
# and therefore require credentials to execute correctly.

name: CI-build

# Controls when the workflow will run
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["CI-basic"]
#    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: build
        run:
          make build

      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path:
            dist/dowml-*.whl

  install-and-test:
    needs: build
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: download
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dowml-*.whl

      - name: Check
        env:
          WML_PROD_APIKEY: '${{secrets.WML_PROD_APIKEY}}'
          WML_PROD_URL: '${{secrets.WML_PROD_URL}}'
          WML_PROD_SPACE_ID: '${{secrets.WML_PROD_SPACE_ID}}'
          WML_PROD_COS_CRN: '${{secrets.WML_PROD_COS_CRN}}'
          WML_PROD_ML_CRN: '${{secrets.WML_PROD_ML_CRN}}'
        run: |
          export DOWML_CREDENTIALS="{'apikey': '${WML_PROD_APIKEY}', 'url': '${WML_PROD_URL}', 'cos_resource_crn': '${WML_PROD_COS_CRN}', 'ml_instance_crn': '${WML_PROD_ML_CRN}', 'space_name': 'dowml-test-space' }"
          dowml -c 'jobs'

      - name: store
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dist-checked
          path:
            ./dowml-*.whl
