# A workflow to run tests that actually goes to WML
# and therefore require credentials to execute correctly.

name: CI-build

# Controls when the workflow will run
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["CI-basic"]
#    types: [completed]

jobs:
  build-upload-install-test:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Runs a single command using the runners shell
      - name: build
        run:
          make build

      - name: store
        uses: actions/upload-artifact@v2
          with:
            name: dist
            path:
              dist
