# A workflow to run tests that actually goes to WML
# and therefore require credentials to execute correctly.

name: CI-build

on:
  workflow_run:
    workflows: ["CI-unit-tests"]
    types: [completed]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a single command using the runners shell
      - name: Run full tests
        env:
          WML_PROD_APIKEY: '${{secrets.WML_PROD_APIKEY}}'
          WML_PROD_URL: '${{secrets.WML_PROD_URL}}'
          WML_PROD_SPACE_ID: '${{secrets.WML_PROD_SPACE_ID}}'
          WML_PROD_COS_CRN: '${{secrets.WML_PROD_COS_CRN}}'
          WML_PROD_ML_CRN: '${{secrets.WML_PROD_ML_CRN}}'
        run: |
          export DOWML_CREDENTIALS="{'apikey': '${WML_PROD_APIKEY}', 'url': '${WML_PROD_URL}', 'cos_resource_crn': '${WML_PROD_COS_CRN}', 'ml_instance_crn': '${WML_PROD_ML_CRN}', 'space_name': 'dowml-test-space' }"
          cd tests
          make basic
          make slow
          make fulltests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: build
        run: |
          make build
          echo ${{github.sha}} > dist/version.info

      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path:
            dist/*

  install-and-test:
    needs: build
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dist/dowml-*.whl

      - name: Check
        env:
          WML_PROD_APIKEY: '${{secrets.WML_PROD_APIKEY}}'
          WML_PROD_URL: '${{secrets.WML_PROD_URL}}'
          WML_PROD_SPACE_ID: '${{secrets.WML_PROD_SPACE_ID}}'
          WML_PROD_COS_CRN: '${{secrets.WML_PROD_COS_CRN}}'
          WML_PROD_ML_CRN: '${{secrets.WML_PROD_ML_CRN}}'
        run: |
          export DOWML_CREDENTIALS="{'apikey': '${WML_PROD_APIKEY}', 'url': '${WML_PROD_URL}', 'cos_resource_crn': '${WML_PROD_COS_CRN}', 'ml_instance_crn': '${WML_PROD_ML_CRN}', 'space_name': 'dowml-test-space' }"
          dowml -c 'jobs'

      - name: store
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dist-checked
          path:
            ./dist/*

  tag:
    needs: install-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: download
        uses: actions/download-artifact@v2
        with:
          name: dist-checked
          path: dist-checked

      - name: store-version-info
        run: |
          VERSION=`ls -1 dist-checked/dowml-*.tar.gz | sed 's#dist-checked/dowml-##' | sed 's/.tar.gz//'`
          GITID=`cat dist-checked/version.info`
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -f V${VERSION}-latest-build ${GITID}
          git push --tags
